=== el-oso/XmlStructTools.jl/docs/examples/orders.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:Orders="Orders" targetNamespace="Orders">

    <element name="orders" type="Orders:OrdersType"/>

    <simpleType name="Sku">
        <annotation>
            <documentation>A product code: three capital letters, a dash and four digits.</documentation>
        </annotation>
        <restriction base="string">
            <pattern value="[A-Z]{3}-[0-9]{4}"/>
        </restriction>
    </simpleType>

    <simpleType name="Quantity">
        <restriction base="integer">
            <minInclusive value="1"/>
        </restriction>
    </simpleType>

    <complexType name="Line">
        <annotation>
            <documentation>One product in an order.</documentation>
        </annotation>
        <sequence>
            <element name="sku" type="Orders:Sku"/>
            <element name="quantity" type="Orders:Quantity"/>
            <element name="price" type="decimal"/>
            <element name="note" type="string" minOccurs="0"/>
        </sequence>
    </complexType>

    <complexType name="Order">
        <sequence>
            <element name="id" type="string"/>
            <element name="placed" type="dateTime"/>
            <choice>
                <element name="email" type="string"/>
                <element name="phone" type="string"/>
            </choice>
            <element name="line" type="Orders:Line" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

    <complexType name="OrdersType">
        <sequence>
            <element name="order" type="Orders:Order" maxOccurs="unbounded"/>
        </sequence>
    </complexType>

</schema>

=== el-oso/XmlStructTools.jl/docs/examples/orders.xml
<?xml version="1.0" encoding="utf-8"?>
<Orders:orders xmlns:Orders="Orders" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="Orders orders.xsd">
    <order>
        <id>A-1001</id>
        <placed>2026-03-02T09:15:00</placed>
        <email>ada@example.com</email>
        <line>
            <sku>KBD-0042</sku>
            <quantity>2</quantity>
            <price>49.90</price>
        </line>
        <line>
            <sku>MSE-0007</sku>
            <quantity>1</quantity>
            <price>19.50</price>
            <note>gift wrap</note>
        </line>
    </order>
    <order>
        <id>A-1002</id>
        <placed>2026-03-02T11:40:00+01:00</placed>
        <phone>+31 40 123 4567</phone>
        <line>
            <sku>MON-0100</sku>
            <quantity>1</quantity>
            <price>229.00</price>
        </line>
    </order>
</Orders:orders>
