=== el-oso/XmlStructTools.jl/XmlStructLoader.jl/test/test_data/edge_cases/renamed_elements.xsd
<?xml version="1.0"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:TestRenamedElements="TestRenamedElements" targetNamespace="TestRenamedElements">

<element name="document" type="TestRenamedElements:documentType"/>

<complexType name="record-type">
    <annotation>
        <documentation>A complex type whose name and element names are not Julia identifiers.</documentation>
    </annotation>
    <sequence>
        <element name="Element-string" type="string"/>
        <element name="Element-double" type="double"/>
    </sequence>
</complexType>

<complexType name="documentType">
    <sequence>
        <element name="single-record" type="TestRenamedElements:record-type"/>
        <element name="repeated-record" type="TestRenamedElements:record-type" maxOccurs="unbounded"/>
        <element name="plain" type="string"/>
    </sequence>
</complexType>

</schema>

=== el-oso/XmlStructTools.jl/XmlStructWriter.jl/test/test_data/mapping_cases/renamed_elements.xml
<?xml version="1.0" encoding="utf-8"?>
<TestRenamedElements:document xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="TestRenamedElements renamed_elements.xsd" xmlns:TestRenamedElements="TestRenamedElements">
    <single-record>
        <Element-string>one</Element-string>
        <Element-double>1.5</Element-double>
    </single-record>
    <repeated-record>
        <Element-string>two</Element-string>
        <Element-double>2.5</Element-double>
    </repeated-record>
    <repeated-record>
        <Element-string>three</Element-string>
        <Element-double>3.5</Element-double>
    </repeated-record>
    <plain>text</plain>
</TestRenamedElements:document>
